# Generated by Django 4.2.5 on 2023-09-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('d_speciality', models.CharField(max_length=100)),
                ('d_status', models.CharField(max_length=100)),
                ('d_location', models.CharField(max_length=100)),
                ('d_cost', models.IntegerField()),
                ('d_days', models.CharField(max_length=100)),
                ('d_startTime', models.TimeField()),
                ('d_endTime', models.TimeField()),
                ('d_rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('h_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=100)),
                ('h_location', models.CharField(max_length=100)),
                ('h_phone', models.CharField(max_length=100, unique=True)),
                ('h_icuStatus', models.CharField(max_length=100)),
                ('h_bloodGroup1', models.CharField(max_length=100)),
                ('h_bloodGroup2', models.CharField(max_length=100)),
                ('h_bloodGroup3', models.CharField(max_length=100)),
                ('h_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('r_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=100)),
                ('r_description', models.CharField(max_length=100)),
                ('r_permission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_age', models.CharField(max_length=3)),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_address', models.CharField(max_length=100)),
                ('u_gender', models.CharField(max_length=100)),
                ('u_mobile', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAccessories',
            fields=[
                ('acc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_type', models.CharField(max_length=100)),
                ('acc_cost', models.IntegerField()),
                ('acc_count', models.IntegerField()),
                ('seller_id', models.CharField(max_length=10)),
                ('seller1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_sold', to='myApp.user')),
            ],
            options={
                'unique_together': {('acc_id', 'seller_id')},
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('a_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('a_type', models.CharField(max_length=100)),
                ('a_cost', models.IntegerField()),
                ('a_location', models.CharField(max_length=100)),
                ('a_status', models.CharField(max_length=100)),
                ('a_number', models.CharField(max_length=10, unique=True)),
                ('driver_id', models.CharField(max_length=10)),
                ('driver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances_driven', to='myApp.user')),
            ],
            options={
                'unique_together': {('a_id', 'driver_id')},
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10)),
                ('a_id', models.CharField(max_length=10)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_taken', to='myApp.ambulance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances_taken', to='myApp.user')),
            ],
            options={
                'unique_together': {('u_id', 'a_id')},
            },
        ),
        migrations.CreateModel(
            name='Goes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=10)),
                ('a_id', models.CharField(max_length=10)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals_arrived', to='myApp.ambulance')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances_arrived', to='myApp.hospital')),
            ],
            options={
                'unique_together': {('h_id', 'a_id')},
            },
        ),
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10)),
                ('acc_id', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('totalCost', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='myApp.medicalaccessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_bought', to='myApp.user')),
            ],
            options={
                'unique_together': {('u_id', 'acc_id')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('app_type', models.CharField(max_length=100)),
                ('app_time', models.CharField(max_length=100)),
                ('indv_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('u_id', models.CharField(max_length=10)),
                ('d_id', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myApp.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myApp.user')),
            ],
            options={
                'unique_together': {('u_id', 'd_id')},
            },
        ),
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=10)),
                ('u_id', models.CharField(max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='myApp.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='myApp.user')),
            ],
            options={
                'unique_together': {('h_id', 'u_id')},
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=10)),
                ('u_id', models.CharField(max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_access', to='myApp.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='myApp.user')),
            ],
            options={
                'unique_together': {('r_id', 'u_id')},
            },
        ),
    ]
