# Generated by Django 4.2.5 on 2023-09-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_description', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_cost', models.IntegerField()),
                ('p_count', models.IntegerField()),
                ('v_name', models.CharField(max_length=100)),
                ('v_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_password', models.CharField(max_length=100)),
                ('u_age', models.CharField(max_length=3)),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_address', models.CharField(max_length=100)),
                ('u_gender', models.CharField(max_length=100)),
                ('u_mobile', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalCost', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='myApp.medicalaccessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_bought', to='myApp.user')),
            ],
        ),
    ]
