# Generated by Django 4.2.5 on 2023-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_medicalaccessories_p_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalaccessories',
            name='p_image',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
