# Generated by Django 4.2.5 on 2023-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_cartitem_total_cost_delete_buys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
