# Generated by Django 4.2.5 on 2023-09-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_medicalaccessories_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaccessories',
            name='p_image',
            field=models.ImageField(upload_to='static/product_image'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.medicalaccessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
    ]
