# Generated by Django 4.2.5 on 2023-09-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_bill_alter_medicalaccessories_p_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.medicalaccessories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
