# Generated by Django 4.2.5 on 2023-09-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0007_remove_bill_accessory_remove_bill_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='bill',
            name='accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.medicalaccessories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
