# Generated by Django 4.2.5 on 2023-09-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
