# Generated by Django 4.2.5 on 2023-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_medicalaccessories_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaccessories',
            name='p_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
