# Generated by Django 4.2.5 on 2023-09-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_appointment_created_at_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_spots',
            field=models.PositiveIntegerField(),
        ),
    ]
