# Generated by Django 4.2.5 on 2023-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_appointment_doctor_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslot',
            name='end_day',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctortimeslot',
            name='start_day',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
