# Generated by Django 4.2.5 on 2023-09-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_doctortimeslot_end_day_doctortimeslot_start_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortimeslot',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='doctortimeslot',
            name='start_day',
        ),
    ]
