# Generated by Django 4.2.6 on 2023-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_remove_blood_rh_factor_alter_blood_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='blood_samples',
            field=models.ManyToManyField(related_name='hospitals', to='myApp.blood'),
        ),
    ]
