# Generated by Django 4.2.6 on 2023-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_remove_blood_hospital_hospital_blood_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_available_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
