# Generated by Django 4.2.6 on 2023-12-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_remove_bill_accessory_remove_bill_quantity_billitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
